#!/usr/bin/env python3
"""
Inline app.css into every page that uses it.

WHY
On 2026-09-14 the landing page and the workspace had drifted to 19 font sizes
and 21 tracking values between them, including -.010em and -.01em written as two
rules for the same number. Neither file was wrong on its own. They had simply
never been compared, because nothing compared them.

Published artifacts and single-file mockups cannot link a stylesheet, so the CSS
has to be copied in. Copying by hand is what caused the drift. This copies it.

USE
    python3 sync-styles.py          write app.css into every page
    python3 sync-styles.py --check  exit 1 if any page is out of date

Never hand-edit the CSS inside an HTML file. Edit app.css and run this.
"""
import sys, pathlib, re

HERE = pathlib.Path(__file__).parent
SOURCE = HERE / "app.css"
PAGES = ["workspace.html", "landing-page.html"]

START = "/* == app.css start =="
END = "== app.css end == */"


def block(css: str) -> str:
    return f"{START} generated by sync-styles.py, do not edit here ==*/\n{css}\n/*{END}"


def current(html: str):
    """The app.css block in a page, or None if it has never been synced."""
    m = re.search(re.escape(START) + r".*?" + re.escape(END), html, re.S)
    return m


def main() -> int:
    check = "--check" in sys.argv
    css = SOURCE.read_text(encoding="utf-8").strip()
    want = block(css)
    stale = []

    for name in PAGES:
        page = HERE / name
        if not page.exists():
            print(f"  ?  {name} missing")
            continue
        html = page.read_text(encoding="utf-8")
        found = current(html)

        if found is None:
            print(f"  !  {name} has no app.css markers, so it has never been synced")
            stale.append(name)
            continue

        if found.group(0).strip() == want.strip():
            print(f"  ok {name}")
            continue

        stale.append(name)
        if check:
            print(f"  !  {name} is out of date")
        else:
            page.write_text(html[: found.start()] + want + html[found.end():], encoding="utf-8")
            print(f"  -> {name} updated")

    if check and stale:
        print(f"\n{len(stale)} page(s) out of date. Run: python3 sync-styles.py")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
