#!/usr/bin/env python3
"""
Inline the resizer's geometry into the page.

WHY
`src/preview.js` in the Content & Social Planner holds the crop and preview
maths. It is tested there with real numbers, because the two bugs Raj found in
the resizer were both geometric and every test that read the page's source
passed straight through them.

A page cannot import a module, so the file is copied in between markers. Copying
by hand is how two implementations of one rule start disagreeing, which is
exactly what happened to the Competitor Tracker's candidate check. This copies
it, and --check fails when the copy has gone stale.

USE
    python3 sync-preview.py          write preview.js into the page
    python3 sync-preview.py --check  exit 1 if the page is out of date

Never hand-edit the inlined block. Edit src/preview.js and run this.
"""
import sys, pathlib, re

HERE = pathlib.Path(__file__).parent
SOURCE = HERE.parent / "Agents" / "Content & Social Planner" / "src" / "preview.js"
PAGE = HERE / "workspace.html"
START = "/* == preview.js start =="
END = "== preview.js end == */"


def as_script(js: str) -> str:
    """The same source, minus the module exports.

    `preview.js` holds the crop and preview geometry, and two things need it:
    this page, which runs it as a classic script, and the web app, which imports
    it as a module. A classic script throws a SyntaxError on `export`, and an
    `export` cannot be written conditionally, so the one source keeps its
    exports and the inliner takes them out on the way in.

    The alternative was a second copy of the geometry in `web/`, and two copies
    of one rule is the defect this project has now found in the engine, the
    screen, the running panel, the channel names and the image sizes.
    """
    kept = [l for l in js.splitlines() if not l.lstrip().startswith("export ")]
    return "\n".join(kept).strip()


def block(js: str) -> str:
    return f"{START} generated by sync-preview.py, do not edit here ==*/\n{as_script(js)}\n/*{END}"


def main() -> int:
    check = "--check" in sys.argv
    js = SOURCE.read_text(encoding="utf-8").strip()
    want = block(js)
    html = PAGE.read_text(encoding="utf-8")
    found = re.search(re.escape(START) + r".*?" + re.escape(END), html, re.S)

    if found is None:
        print(f"  !  {PAGE.name} has no preview.js markers, so it has never been synced")
        return 1
    if found.group(0).strip() == want.strip():
        print(f"  ok {PAGE.name}")
        return 0
    if check:
        print(f"  !  {PAGE.name} is out of date. Run: python3 sync-preview.py")
        return 1
    PAGE.write_text(html[: found.start()] + want + html[found.end():], encoding="utf-8")
    print(f"  -> {PAGE.name} updated")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
